// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.DwhExternalBalances.DataBase;

#nullable disable

namespace Service.DwhExternalBalances.DataBase.Migrations
{
    [DbContext(typeof(DwhContext))]
    partial class DwhContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("data")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Service.DwhExternalBalances.Domain.Models.ExternalBalance", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Asset")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Type", "Name", "Asset");

                    b.ToTable("AllExternalBalances", "data");
                });

            modelBuilder.Entity("Service.DwhExternalBalances.Domain.Models.ExternalBalanceHistory", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Asset")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestemp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Type", "Name", "Asset", "Timestemp");

                    b.ToTable("AllExternalBalancesHistory", "data");
                });
#pragma warning restore 612, 618
        }
    }
}
